version: 2
updates:
  # GitHub Actions in /.github/workflows/ # TODO exclude mt-sync-code-data.yml (already setup in commons repo)
  - package-ecosystem: "github-actions"
    directory: "/" # == "/.github/workflows/"
    schedule:
      interval: "weekly"
