version: 2
updates:
  # GitHub Actions in /.github/workflows/ # TODO exclude mt-sync-code-data.yml (already setup in commons repo)
  - package-ecosystem: "github-actions"
    # "/" == "/.github/workflows/"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "mmathieum"
